### ISSUE TITLE
3 new bugs found

### ISSUE THREAD

**Issue by Bobobaal** [gorbb/QwickTree#2]
First bug: My tree is not connected to any part of the little house but I get spammed that I may break a block of a house.
http://prntscr.com/96xlde

Second bug: My config says saplings but I get leaves in my inv:
Inventory: http://prntscr.com/96xmdt
config: http://prntscr.com/96xmmu

Third bug found: if replant is on and you plant a tree and you place logs on the ground connected to the tree then this happens:
http://prntscr.com/96y1jh

**Comment by Bobobaal** [comment]
Second bug doesn't happen anymore.

**Comment by gorbb** [comment]
Hi, both the first and third issues are funny quirks of how the plugin works.

Since the leaf reach for a large jungle tree is high, so is its checking for the house blocks. It should be relatively simple to alter this behaviour.

The third one is because of the way blocks attached to the ground are dealt with.
There's no direct solution to this, but the most sound solution to me would be to simply add a limit to the number of saplings that can be replanted.

**Comment by gorbb** [comment]
New version has been uploaded and is pending approval.
