### ISSUE TITLE
No Trees Cut Down

### ISSUE THREAD

**Issue by D17A1** [gorbb/QwickTree#4]
Permissions are blank, only plugin installed is QwickTree
![image](https://cloud.githubusercontent.com/assets/16854065/12531210/bd8fcfc2-c1c2-11e5-91cb-70cabb466c5f.png)

This is result of chopping a tree with a diamond axe

**Comment by gorbb** [comment]
Hello,

The reason for this issue is that the player doesn't have permission to chop down the tree. The default config is set to work with permissions plugins, so you need to either give players the _qwicktree.use_ permission or (if you aren't using a permissions plugin) set **usePerms** to false in the config.

**Comment by D17A1** [comment]
thank you
