### ISSUE TITLE
Damage Type

### ISSUE THREAD

**Issue by jetafix** [gorbb/QwickTree#8]
Hello!
First, let me say that my english isnt very good...
Im very satysfied that i foung plugin like your, its awesome, another just didnt worked. Your worked at 1st attempt, so i was sooooo happy. Im editing my config now, but i dont know how work the damage type config...
I know that you described it in config page, but i dont see real in game differences, bcs i dont have any invtweaks or something to show me durability. Can you help me and describe more which option do what? I want to set, that chopping the tree will make that much dmg - how much blocks were broken...
Greetings from Poland and thank you for your time and help :)

**Comment by gorbb** [comment]
Hello jetafix!

I'm pleased to hear that you like QwickTree. The idea behind setting the damage types is to allow you to specify in detail what happens to an axe when a tree is chopped down.

Durability is only applied to items which can take damage, such as axes, swords, etc. Things that don't take damage like a sapling won't take any durability damage.

There are four types of damage:

### None
The axe (or other item) takes no damage from chopping trees

### NORM
The axe/item takes 1 durability damage for each log chopped, the same as if they chopped the tree manually. This is the default option.

### FIXED
The axe/item takes a fixed amount of damage whenever a tree is chopped, without taking into account the amount of logs in the tree.
For example, if *damage.amount* is set to 10, then chopping that tree type will cause 10 damage to be applied to the item, whether it has 4 logs or 40.

### MULT
The axe/item takes a **multiple** of the amount of each log chopped of damage.
If *damage.amount* is set to 3, then chopping a tree with 10 logs will cause 30 damage to be applied.

Setting the damage type to any of these options changes how much chopping a tree 'costs' a player. It's worth noting that having a durability enchantment on an item does also reduce the amount of damage done to it, in the same way as it already does in Minecraft.

Setting damage type to NONE is useful for some roleplay servers or if other plugins are used to determine damage to items - or if you simply don't want to charge players for cutting down trees.
Setting to NORM is the default option and the most recommended one for vanilla servers, however since using this plugin makes it easier and quicker to chop trees, you could offset that ease of use by making it use up axes quicker - setting damage type to MULT.

This is rather a large comment and I hope it helps you understand how it works. Let me know if you need anything else. :)

**Comment by gorbb** [comment]
Hi jetafix,

This ticket is a week old, so I'll close it now. I hope I managed to help - feel free to re-open this ticket if you need anything else.
